version: '3.4'
services:
  node-app:
    build:
      context: .
      args:
       - NODE_ENV= development
    volumes:
      - ./:/app
      -  /app/node_modules
    environment:
      - NODE_ENV=development  
    command: npm start